Add option to specify php version

diff --git a/laravel-helper b/laravel-helper
--- a/laravel-helper
+++ b/laravel-helper
@@ -1,4 +1,4 @@
-#! /bin/bash
+#!/bin/bash
 
 e() {
     RED='\033[0;31m'
@@ -8,12 +8,11 @@ e() {
     NC='\033[0m'
 
     TXT_COLOR="${!2}"
-    echo "${TXT_COLOR}$1${NC}"
+    echo -e "${TXT_COLOR}$1${NC}"
 }
 
-
 help() {
-    echo -e "$(e "### Help ###\n" "YELLOW")" 
+    echo -e "$(e "### Help ###\n" "YELLOW")"
 
     echo -e "$(e "d - Target directory (eg: -d /opt/my-laravel)" "YELLOW")"
     echo -e "$(e "u - Update code using git pull (defaults to master branch)" "YELLOW")"
@@ -23,6 +22,7 @@ help() {
     echo -e "$(e "f - Refresh laravel instance" "YELLOW")"
     echo -e "$(e "t - Output Laravel log file with specified line number (eg: -t 100 to output last 100 line)" "YELLOW")"
     echo -e "$(e "l - Output Laravel log file and append output as log file grow" "YELLOW")"
+    echo -e "$(e "p - Specify PHP version to use temporarily (eg: -p 8.1)" "YELLOW")"
 
     exit 0
 }
@@ -37,25 +37,45 @@ check_deploy_dir() {
             echo -e "\nExiting..."
             exit 1
         fi
-    else
-        DEPLOY_DIR="${DEPLOY_DIR}"
+    fi
+}
+
+switch_php_version() {
+    if [[ -n "$PHP_VERSION" ]]; then
+        echo -e "$(e "Switching to PHP $PHP_VERSION" "YELLOW")"
+        PHP_PATH="/usr/bin/php$PHP_VERSION"
+        if [[ ! -f "$PHP_PATH" ]]; then
+            echo -e "$(e "Error: PHP version $PHP_VERSION is not installed on this system." "RED")"
+            exit 1
+        fi
+
+        ORIGINAL_PHP=$(update-alternatives --query php | grep Value: | awk '{print $2}' | head -n 1)
+        sudo update-alternatives --set php /usr/bin/php$PHP_VERSION
+        PHP_CHANGED=true
+    fi
+}
+
+revert_php_version() {
+    if [[ "$PHP_CHANGED" == true ]]; then
+        echo -e "$(e "Reverting to original PHP version" "YELLOW")"
+        sudo update-alternatives --set php $ORIGINAL_PHP
     fi
 }
 
 update() {
-    echo -e "$(e "Updating code in $DEPLOY_DIR\n" "YELLOW")" 
+    echo -e "$(e "Updating code in $DEPLOY_DIR\n" "YELLOW")"
     git checkout -- .
     git pull
 }
 
 install() {
-    echo -e "$(e "Installing dependencies\n" "YELLOW")" 
+    echo -e "$(e "Installing dependencies\n" "YELLOW")"
     composer install
     php artisan migrate
 }
 
 reset() {
-    echo -e "$(e "Reset folder permissions\n" "YELLOW")" 
+    echo -e "$(e "Reset folder permissions\n" "YELLOW")"
     sudo chgrp -R www-data . && sudo chmod -R 775 storage && sudo chmod -R 775 bootstrap/cache
 }
 
@@ -69,7 +89,7 @@ cache_config() {
 }
 
 tail_line() {
-    echo -e "$(e "Laravel log\n" "YELLOW")" 
+    echo -e "$(e "Laravel log\n" "YELLOW")"
     FILE="storage/logs/laravel-$(date +%Y-%m-%d).log"
     FILE2="storage/logs/laravel.log"
     if [ -f "$FILE" ]; then
@@ -80,7 +100,7 @@ tail_line() {
 }
 
 tail_follow() {
-    echo -e "$(e "Laravel log\n" "YELLOW")" 
+    echo -e "$(e "Laravel log\n" "YELLOW")"
     FILE="storage/logs/laravel-$(date +%Y-%m-%d).log"
     FILE2="storage/logs/laravel.log"
     if [ -f "$FILE" ]; then
@@ -94,20 +114,22 @@ if [[ $# == 0 ]]; then
     help
 fi
 
-while getopts "hd:uicrft:l" OPTION; do
+PHP_CHANGED=false
+while getopts "hd:uicrft:lp:" OPTION; do
     case $OPTION in
         h ) help ;;
         d ) DEPLOY_DIR="$OPTARG" ;;
+        p ) PHP_VERSION="$OPTARG" ;;
     esac
 done
-
-OPTIND=1
 
 check_deploy_dir
 
 pushd $DEPLOY_DIR
 
-while getopts "hd:uicrft:l" OPTION; do
+switch_php_version
+
+while getopts "hd:uicrft:lp:" OPTION; do
     case $OPTION in
     u ) update ;;
     i ) install ;;
@@ -120,3 +142,4 @@ while getopts "hd:uicrft:l" OPTION; do
 done
 
 popd
+revert_php_version
